// Auto-generated by ThrusterHelper.jl export_cpp(); do not edit by hand.
// Vehicle: BlueROV2 Heavy  |  method: minimum_norm  |  actuators: 8
//
// Generic, self-contained actuator allocation for any AUV/ROV/vehicle.
// The matrix below is this vehicle's pinv(B) (or weighted variant),
// precomputed once in Julia; at runtime this header only does a fixed-
// size matrix-vector multiply and a direction-preserving scale to
// limits. O(N), no heap allocation, no iteration, no dependency on
// Julia or ThrusterHelper. Wire allocate() into any control loop.
#ifndef THRUSTER_ALLOCATION_HPP
#define THRUSTER_ALLOCATION_HPP

#include <array>
#include <cmath>
#include <cstddef>

namespace thruster_allocation {

constexpr std::size_t kNumActuators = 8;
constexpr std::size_t kNumDof = 6; // Fx, Fy, Fz, taux, tauy, tauz

constexpr const char* kActuatorNames[kNumActuators] = { "front-right-horiz", "front-left-horiz", "back-right-horiz", "back-left-horiz", "front-right-vert", "front-left-vert", "back-right-vert", "back-left-vert" };
constexpr float kMaxCommand[kNumActuators] = { 1.000000000f, 1.000000000f, 1.000000000f, 1.000000000f, 1.000000000f, 1.000000000f, 1.000000000f, 1.000000000f };

// Row i = actuator i's weights across [Fx, Fy, Fz, taux, tauy, tauz].
constexpr float kAllocationInverse[kNumActuators][kNumDof] = {
        {0.353553391f, 0.353553391f, 0.000000000f, 0.000000000f, 0.000000000f, 0.803530433f},
        {0.353553391f, -0.353553391f, 0.000000000f, 0.000000000f, 0.000000000f, -0.803530433f},
        {-0.353553391f, 0.353553391f, 0.000000000f, 0.000000000f, 0.000000000f, -0.803530433f},
        {-0.353553391f, -0.353553391f, 0.000000000f, 0.000000000f, 0.000000000f, 0.803530433f},
        {0.000000000f, 0.000000000f, 0.250000000f, -1.136363636f, -1.136363636f, 0.000000000f},
        {0.000000000f, 0.000000000f, 0.250000000f, 1.136363636f, -1.136363636f, 0.000000000f},
        {0.000000000f, 0.000000000f, 0.250000000f, -1.136363636f, 1.136363636f, 0.000000000f},
        {0.000000000f, 0.000000000f, 0.250000000f, 1.136363636f, 1.136363636f, 0.000000000f},
};

// Solve for actuator commands producing the desired wrench `tau`.
// O(kNumActuators * kNumDof). Scales the result to kMaxCommand (see below).
inline std::array<float, kNumActuators> allocate(const std::array<float, kNumDof>& tau) noexcept {
    std::array<float, kNumActuators> f{};
    for (std::size_t i = 0; i < kNumActuators; ++i) {
        float sum = 0.0f;
        for (std::size_t k = 0; k < kNumDof; ++k) sum += kAllocationInverse[i][k] * tau[k];
        f[i] = sum;
    }
    // Direction-preserving scale to stay within kMaxCommand (mirrors
    // ThrusterHelper.jl's scale_to_limits). Regenerate with
    // export_cpp(...; saturate=false) to return the raw commands.
    float worst = 1.0f;
    for (std::size_t i = 0; i < kNumActuators; ++i) {
        float ratio = std::fabs(f[i]) / kMaxCommand[i];
        if (ratio > worst) worst = ratio;
    }
    if (worst > 1.0f) {
        for (std::size_t i = 0; i < kNumActuators; ++i) f[i] /= worst;
    }
    return f;
}

} // namespace thruster_allocation

#endif // THRUSTER_ALLOCATION_HPP
