// allocator_node.cpp
// A minimal ROS 2 (rclcpp) node that wraps the header generated by
// ThrusterHelper.jl's export_cpp(). It subscribes to a desired wrench and
// publishes the per-thruster commands, doing the allocation as the header's
// fixed-size matrix-vector multiply (O(N), no heap, no Julia at runtime).
//
// Topic interface (both remappable, see the parameters below):
//   sub  geometry_msgs/msg/Wrench   on  "cmd_wrench"
//   pub  std_msgs/msg/Float64MultiArray on "thruster_commands"
//
// The published array is ordered to match kActuatorNames in the header.

#include <array>
#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
#include "geometry_msgs/msg/wrench.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"

#include "thruster_allocation.hpp"

namespace ta = thruster_allocation;

class AllocatorNode : public rclcpp::Node {
public:
  AllocatorNode() : rclcpp::Node("thruster_allocator") {
    const auto in_topic  = declare_parameter<std::string>("input_topic", "cmd_wrench");
    const auto out_topic = declare_parameter<std::string>("output_topic", "thruster_commands");

    pub_ = create_publisher<std_msgs::msg::Float64MultiArray>(out_topic, 10);
    sub_ = create_subscription<geometry_msgs::msg::Wrench>(
        in_topic, 10,
        [this](const geometry_msgs::msg::Wrench::SharedPtr msg) { on_wrench(*msg); });

    // Label the array dimension with the actuator count so downstream nodes can
    // sanity-check length; names live in kActuatorNames for reference.
    layout_.dim.resize(1);
    layout_.dim[0].label = "thruster";
    layout_.dim[0].size = ta::kNumActuators;
    layout_.dim[0].stride = ta::kNumActuators;

    RCLCPP_INFO(get_logger(), "thruster_allocator: %zu actuators, '%s' -> '%s'",
                ta::kNumActuators, in_topic.c_str(), out_topic.c_str());
  }

private:
  void on_wrench(const geometry_msgs::msg::Wrench &w) {
    const std::array<float, ta::kNumDof> tau = {
        static_cast<float>(w.force.x),  static_cast<float>(w.force.y),
        static_cast<float>(w.force.z),  static_cast<float>(w.torque.x),
        static_cast<float>(w.torque.y), static_cast<float>(w.torque.z)};

    const auto f = ta::allocate(tau);

    std_msgs::msg::Float64MultiArray out;
    out.layout = layout_;
    out.data.assign(f.begin(), f.end());
    pub_->publish(out);
  }

  rclcpp::Subscription<geometry_msgs::msg::Wrench>::SharedPtr sub_;
  rclcpp::Publisher<std_msgs::msg::Float64MultiArray>::SharedPtr pub_;
  std_msgs::msg::MultiArrayLayout layout_;
};

int main(int argc, char **argv) {
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<AllocatorNode>());
  rclcpp::shutdown();
  return 0;
}
