# export_cpp.jl
# Generate a self-contained, dependency-free C++17 header that does this
# vehicle's allocation as a precomputed matrix-vector multiply, O(N): no
# heap, no iteration, no runtime dependency on Julia or this package. Vehicle-
# agnostic: works for any AUV/ROV/actuator layout, not tied to one project.
#
# Only :minimum_norm and :weighted export: both reduce to a fixed N×6 matrix
# once geometry (and weights) are chosen at generation time. :qp and
# :minimum_power are iterative solves with no constant-matrix form.

"""
    export_cpp(vehicle; method=:minimum_norm, weights=nothing, saturate=true,
               path=nothing, namespace="thruster_allocation") -> String

Generate a self-contained C++17 header implementing `vehicle`'s allocation as a
`constexpr` matrix bake-in. Depends only on `<array>`, `<cmath>`, `<cstddef>`, so
drop it into any flight controller, ROS 2 node, or bare-metal firmware for any
AUV/ROV, independent of this package at runtime.

Only `:minimum_norm` (default) / `:pinv` and `:weighted` are supported;
`:qp`/`:minimum_power` are iterative and have no constant-matrix form.

By default (`saturate=true`) the generated `allocate()` applies a
direction-preserving scale to `kMaxCommand` (mirrors [`scale_to_limits`](@ref)),
so its output can differ from the Julia `allocate(vehicle, τ; method=…)` of the
same method, which returns the *raw* least-squares commands and does not clamp.
Pass `saturate=false` to omit the clamp and reproduce the Julia `allocate`
output exactly (commands may then exceed `kMaxCommand`).

Writes to `path` if given; always returns the generated source as a `String`.
"""
function export_cpp(v::Vehicle; method::Symbol=:minimum_norm, weights=nothing,
                    saturate::Bool=true,
                    path=nothing, namespace::AbstractString="thruster_allocation")
    method in (:minimum_norm, :pinv, :weighted) ||
        throw(ArgumentError("export_cpp supports :minimum_norm or :weighted only " *
                            "(got :$method); :qp/:minimum_power are iterative, not a constant matrix"))
    B = allocation_matrix(v)
    if method === :weighted
        w = _check_weights(weights, size(B, 2))
        Winv = Diagonal(1 ./ w)
        M = Winv * pinv(B * Winv)
    else
        M = pinv(B)
    end
    n = size(M, 1)
    limits = max_thrusts(v)
    names = [label(a) for a in v.actuators]
    guard = uppercase(replace(namespace, r"[^A-Za-z0-9]" => "_")) * "_HPP"

    f(x) = @sprintf("%.9ff", x)
    matrix_lines = join(("        {" * join(f.(M[i, :]), ", ") * "}," for i in 1:n), "\n")
    limit_line = join(f.(limits), ", ")
    name_line = join(("\"" * replace(nm, "\"" => "\\\"") * "\"" for nm in names), ", ")

    # Optional direction-preserving scale to limits (mirrors scale_to_limits).
    sat_lines = saturate ? String[
        "    // Direction-preserving scale to stay within kMaxCommand (mirrors",
        "    // ThrusterHelper.jl's scale_to_limits). Regenerate with",
        "    // export_cpp(...; saturate=false) to return the raw commands.",
        "    float worst = 1.0f;",
        "    for (std::size_t i = 0; i < kNumActuators; ++i) {",
        "        float ratio = std::fabs(f[i]) / kMaxCommand[i];",
        "        if (ratio > worst) worst = ratio;",
        "    }",
        "    if (worst > 1.0f) {",
        "        for (std::size_t i = 0; i < kNumActuators; ++i) f[i] /= worst;",
        "    }",
    ] : String[
        "    // saturate=false at generation time: returns the raw least-squares",
        "    // commands, matching Julia allocate(...).commands exactly (values",
        "    // may exceed kMaxCommand).",
    ]

    lines = String[
        "// Auto-generated by ThrusterHelper.jl export_cpp(); do not edit by hand.",
        "// Vehicle: $(v.name)  |  method: $method  |  actuators: $n",
        "//",
        "// Generic, self-contained actuator allocation for any AUV/ROV/vehicle.",
        "// The matrix below is this vehicle's pinv(B) (or weighted variant),",
        "// precomputed once in Julia; at runtime this header only does a fixed-",
        "// size matrix-vector multiply and a direction-preserving scale to",
        "// limits. O(N), no heap allocation, no iteration, no dependency on",
        "// Julia or ThrusterHelper. Wire allocate() into any control loop.",
        "#ifndef $guard",
        "#define $guard",
        "",
        "#include <array>",
        "#include <cmath>",
        "#include <cstddef>",
        "",
        "namespace $namespace {",
        "",
        "constexpr std::size_t kNumActuators = $n;",
        "constexpr std::size_t kNumDof = 6; // Fx, Fy, Fz, taux, tauy, tauz",
        "",
        "constexpr const char* kActuatorNames[kNumActuators] = { $name_line };",
        "constexpr float kMaxCommand[kNumActuators] = { $limit_line };",
        "",
        "// Row i = actuator i's weights across [Fx, Fy, Fz, taux, tauy, tauz].",
        "constexpr float kAllocationInverse[kNumActuators][kNumDof] = {",
        matrix_lines,
        "};",
        "",
        "// Solve for actuator commands producing the desired wrench `tau`.",
        "// O(kNumActuators * kNumDof)." *
            (saturate ? " Scales the result to kMaxCommand (see below)." : ""),
        "inline std::array<float, kNumActuators> allocate(const std::array<float, kNumDof>& tau) noexcept {",
        "    std::array<float, kNumActuators> f{};",
        "    for (std::size_t i = 0; i < kNumActuators; ++i) {",
        "        float sum = 0.0f;",
        "        for (std::size_t k = 0; k < kNumDof; ++k) sum += kAllocationInverse[i][k] * tau[k];",
        "        f[i] = sum;",
        "    }",
        sat_lines...,
        "    return f;",
        "}",
        "",
        "} // namespace $namespace",
        "",
        "#endif // $guard",
        "",
    ]
    src = join(lines, "\n")
    path === nothing || write(path, src)
    return src
end
